# Generated by Django 2.1.7 on 2019-04-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='Gallery/')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Article')),
            ],
        ),
    ]
